version: "3"

services:
  client:
    image: pdtg/bsale-front
    hostname: client
  api:
    image: pdtg/bsale-server
    hostname: api
    environment:
      - BSALE_DB_URL=$BSALE_DB_URL
      - BSALE_DB_USER=$BSALE_DB_USER
      - BSALE_DB_PASSWORD=$BSALE_DB_PASSWORD
  nginx:
    image: pdtg/bsale-nginx
    hostname: nginx
    ports:
      - 80:80