version: "3.9"

services:
  client:
    image: bsale-front
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  server:
    image: bsale-back
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"