version: "3"

services:
  client:
    image: pdtg/bsale-front
    hostname: client
    build:
      context: client
      dockerfile: Dockerfile
  api:
    image: pdtg/bsale-server
    hostname: api
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - BSALE_DB_URL=$BSALE_DB_URL
      - BSALE_DB_USER=$BSALE_DB_USER
      - BSALE_DB_PASSWORD=$BSALE_DB_PASSWORD
  nginx:
    image: pdtg/bsale-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    hostname: nginx
    ports:
      - 80:80