version: "3"

services:
  client:
    image: bsale-front
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client/static:/usr/share/nginx/html
    ports:
      - "3000:3000"
  api:
    image: bsale-back
    env_file:
      - ./config/.env
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  nginx:
    image: bsale-nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8083:80